src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
New endpoint `/channel/mpesa/transaction` added, for initiating the mpesa workflow with default settings.
=> Endpoint added for initiating mpesa workflow

pom.xml, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeClientConfiguration.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeProcessStarter.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
Changes in packages fro Zeebe 1.1.0 major upgrade.
=> Zeebe 1.1.0 upgrade

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
- refactor into granular functions (workers and routes)
=> Individual Acknowledgement Workflows

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
- route stub
- start new workflows stub
=> Ack route stub

build.gradle, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
@avikganguly01 
@SubhamPramanik 
Please review
=> stub to implementation

.github/workflows/test.yaml, build.gradle
Enables the junit test platform so tests get run during build, and adds github actions workflow to build on each push
=> Github workflow: build & test project on each push

build.gradle, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
@avikganguly01  : Please review
=> Adding liveness and readiness probes

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
Adding new variables for customisable timer and new variables for enabling/disabling notification flag for success and failure.
Other PRs related to new BPMN (Customisable Timer Variable and Success/Failure Flag):
1. New BPMN and new variables PR : https://github.com/fynarfin/ph-ee-env-template/pull/27
2. Notifications Flag PR: https://github.com/openMF/ph-ee-notifications/pull/35
3. Env Labs PR: https://github.com/fynarfin/ph-ee-env-labs/pull/16
@avikganguly01 @SubhamPramanik @danishjamal104
=> Adding new zeebe variables 

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
Correcting a misspelt zeebe variable for notification success/failure flag.
@avikganguly01 @SubhamPramanik
=> Updating variables for notification failure and success flags

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
Reattempt to fix published zeebe variables for notification success or failure flag
@avikganguly01 @SubhamPramanik
=> Updating zeebe variables for notification success/failure flag

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/camel/utils/AMSProps.java, src/main/java/org/mifos/connector/channel/camel/utils/AMSUtils.java, src/main/resources/application.yml
Added workflow configurations for paygops workflow.
Resolved the comments
@avikganguly01 : Please review
=> Adding configuration for paygops worflow

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
@avikganguly01 : Please review
=> Editing ams selection logic and adding log statements

build.gradle, src/main/java/org/mifos/connector/HealthCheck.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/camel/utils/AMSUtils.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java, src/main/resources/application.yml
- validation and start of paybill workflow
- trimming whitespaces in amount string
@avikganguly01 @fynmanoj
=> validation and confirmation for AMS

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
- Fix for paygops and roster hosturl
@fynmanoj
=> Fix for paygops and roster host

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/resources/application.yml
Updated BPMN name for international remmitance
Added multiple zeebe vars for P2p flow
Added a hack for publishing payee dfspid
Related PRs:
https://github.com/openMF/ph-ee-connector-ams-mifos/pull/15
https://github.com/openMF/ph-ee-connector-gsma-mm/pull/12
https://github.com/openMF/ph-ee-bulk-processor/pull/40
@avikganguly01 @danishjamal104
=> Updating bpmn name and zeebe vars

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
- Changed configuration for urls of paygops and roster
- Removed the tomcat port as it is in env-template
@fynmanoj
=> Host fixed and removed port

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application.yml
- Changed configuration for urls of paygops and roster
- Removed the tomcat port as it is in env-template
@fynmanoj
=> Host fixed and port removed

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/resources/application.yml
Removing hardcoded payee tenant value
=> Removing hardcoded payee tenant value

build.gradle, src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java
* Updated conector-common version.
* Added validation for gsma/transfer api.
=> Added validation for gsm/trasnfer api

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java
1. Added the field Note which is passed as zeebe variable in zeeberworkflow.
2. Which is called in the AMS mifos Deposit API via zeebeworkers.
=> Added field NOTE with value of description for Payee deposit API

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java
Adding new variables  for ams name with enable disable for reporting dashboard
=> add new variable for ams reporting

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeProcessStarter.java, src/main/resources/application.yml
- added gsma dev friendly api
- starting workflow at channel connector
@avikganguly01 @fynmanoj
=> GSMA Transaction api

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
- Changed path for gsma transaction to "/channel/gsma/transaction"
=> Changed path for gsma transaction

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application-bb.yml, src/main/resources/application.yml
Fix for
1. Clientcorrelation Id was coming as null and subsequently failing all test cases and retrunign txn not found
2. To address multiple issues related to override application.yml values
=> Minor bug fix for client id coming as null

Dockerfile
=> Updated the port in dockerfile

src/main/java/org/mifos/connector/channel/api/definition/TxnStateApi.java
=> Updated the txnStateAPI endpoint

build.gradle, src/main/java/org/mifos/connector/channel/GSMA_API/GSMATransferAPI.java, src/main/java/org/mifos/connector/channel/GSMA_API/GSMATransferAPIController.java, src/main/java/org/mifos/connector/channel/api/definition/GSMATransactionApi.java, src/main/java/org/mifos/connector/channel/api/implementation/GSMATransactionApiController.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
1. Added the missing headers for GSMA transaction and transfer API.
2. Updated proper response for GSMA transaction api in routebuilder.
3. Added logic to give appropriate HTTP response code for API
4. Added some todo task in code
=> Fixed GSMA transaction and transfer API after migration

src/main/java/org/mifos/connector/channel/api/definition/TransferApi.java, src/main/java/org/mifos/connector/channel/api/implementation/TransferApiController.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
Refer [PHEE-223](https://fynarfin.atlassian.net/browse/PHEE-223)
[PHEE-223]: https://fynarfin.atlassian.net/browse/PHEE-223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added support for batchId in channel/trasnfer API header

src/main/java/org/mifos/connector/channel/api/definition/ValidationApi.java, src/main/java/org/mifos/connector/channel/api/implementation/ValidationApiController.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/model/ValidationRequestDTO.java, src/main/java/org/mifos/connector/channel/model/ValidationResponseDTO.java
- Migrated account status validation API
- Added request and response DTO
- Tested in postman and Swagger documentation
=> Migrated validation API and Added DTOs

src/main/java/org/mifos/connector/channel/api/implementation/GSMATransactionApiController.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java, src/main/resources/application.yml
- inbound transfer api integration
- publishing zeebe variables
=> Inbound transfer api integration

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
=> Added missing timer

build.gradle, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
=> Using new custom data

src/main/java/org/mifos/connector/channel/GSMA_API/GSMADepositAPI.java, src/main/java/org/mifos/connector/channel/GSMA_API/GSMATransferAPI.java
To avoid 400 bad request as response when not adding client correlation id in header 
=> Making X-CorrelationID optional

src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
- Publishing as string for custom data
=> Publishing as string for custom data

src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
* converted to string while publishing
* null check
=> Publishing as string for custom data (#82)

src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
- converted custom data to string while publishing
=> Converted to string while publishing

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/properties/TenantImplementation.java, src/main/java/org/mifos/connector/channel/properties/TenantImplementationProperties.java, src/main/resources/application-tenants.yml
Feature for tenant based implementation use case for bpmn support
Includes a new yml file 
=> GOV-338: Tenant based implementation usecase for bpmn support

build.gradle
Bumped version for connector common dependency after 1.4.1 release having fix : https://github.com/openMF/ph-ee-connector-common/pull/34
=> Updating connector common version

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeProcessStarter.java, src/main/resources/application.yml
Refactor away paybill keywords from channel connector.
Refactor mpesa {collection) words into inbound transfer verbiage.
=> Removing customer specific logic

build.gradle, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/model/CollectionRequestDTO.java
Jira Ticket : 
https://mifosforge.jira.com/browse/GOV-267
=> [GOV- 267] Publishing Custom Data as zeebe variable

src/main/java/org/mifos/connector/channel/zeebe/ZeebeProcessStarter.java
Jira Ticket : https://mifosforge.jira.com/browse/GOV-264
=> [GOV-264]Added timestamp to zeebe process starter

src/main/java/org/mifos/connector/channel/interceptor/IdInterceptor.java
**Updated the idempotency path list for API as it was not able to reach endpoint**
=> Updating the idempotency api list path

src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java, src/main/resources/application.yml
- Logged tenant in filters
Jira Ticket GOV- 265 : https://mifosforge.jira.com/browse/GOV-265
=> Added loggers for tenant in filters

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
Implementation for [302](https://mifosforge.jira.com/browse/GOV-302)
Related PR:
https://github.com/openMF/ph-ee-env-labs/pull/106
https://github.com/openMF/ph-ee-connector-integration-test/pull/43
=> GOV302: Pre-processing validation of data (well formed data and completeness checks) prior to disbursement

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/model/CollectionRequestDTO.java
* added custom data and published it
* publishing custom data and currency
* publishing custom data and currency
Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-312?atlOrigin=eyJpIjoiZWRhODI4ODAyNTQ5NGE1Y2JlNjZhNGI4NmUzYjFiMWUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
=> Publishing Custom Data as zeebe variable

src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
- Logging client Ip in channel connector.
Steps : https://docs.google.com/document/d/1-PgOwUsM77cbpipI81ZRHt4t9gnQ4ryXsEyRSg4m-lM/edit?usp=sharing
Jira Ticket : https://mifosforge.jira.com/jira/software/c/projects/GOV/issues/GOV-261?jql=project%20%3D%20%22GOV%22%20AND%20assignee%20%3D%20%2261cd59bef3037f0069bc0572%22%20ORDER%20BY%20created%20DESC
=> [GOV-261] Logging client IP

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java, src/main/java/org/mifos/connector/channel/utils/NullUtil.java
- Null check for custom data field
Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-321?atlOrigin=eyJpIjoiZWNmMzhmNWNhYjlhNDhhOTlhMTExYjhhODdkYzlmM2YiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
=> [PHEE-321] Null check for custom data

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
[PHEE-337 Importer ES throwing issue JSONObject[‘payer’] not found](https://fynarfin.atlassian.net/browse/PHEE-337?atlOrigin=eyJpIjoiNzNjMDU5NmVkMmRlNGFhN2E5OTQyMDNkODk5NTIzYzgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-337 Importer ES throwing issue JSONObject['payer'] not found

.circleci/config.yml
- parameterized region for new cluster
Jira Ticket : https://fynarfin.atlassian.net/browse/PHEE-346?atlOrigin=eyJpIjoiY2RhMGRiNzRiYmZhNDcwY2IxMDNmMzhlZWQwYjQ2MjkiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
=> PHEE-346 Parameterised region

config/checkstyle/checkstyle.xml, src/main/java/org/mifos/connector/channel/api/definition/ValidationApi.java, src/main/java/org/mifos/connector/channel/api/implementation/ValidationApiController.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/gsma_api/ChannelGSMAAPIController.java, src/main/java/org/mifos/connector/channel/gsma_api/GSMAAPI.java, src/main/java/org/mifos/connector/channel/interceptor/IdInterceptor.java, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java, src/main/java/org/mifos/connector/channel/utils/Headers.java, src/main/java/org/mifos/connector/channel/utils/SpringWrapperUtil.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeMessages.java
[PHEE-370 Fix checkstyle errors in channel connector](https://fynarfin.atlassian.net/browse/PHEE-370?atlOrigin=eyJpIjoiNzdiMzk3N2ZkNjg0NDA3M2FmMTk3ZTY1YmNhOTczMzMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-370 Resolved checkstyle errors manually

.circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527) Description
=> #GOV-527 test build and push image to dockerhub

src/main/java/org/mifos/connector/channel/utils/AMSUtils.java
[PHEE-378 Remove @utilityclass annotation in channel-connector.](https://fynarfin.atlassian.net/browse/PHEE-378?atlOrigin=eyJpIjoiOWY3NTdjNjhiOTdmNGMzMDllYjJhN2Q4NjViMmY1ZDQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-378 Remove @utilityclass annotation in channel-connector.

.circleci/config.yml, README.md, src/main/java/org/mifos/connector/channel/interceptor/config/WebMvcConfig.java, src/main/java/org/mifos/connector/channel/utils/AMSUtils.java, src/main/java/org/mifos/connector/channel/utils/MpesaUtils.java, src/main/java/org/mifos/connector/channel/utils/SpringWrapperUtil.java, src/test/java/org/mifos/connector/channel/TestUtil.java
[PHEE-374 Update readme for checkstyle and spotless](https://fynarfin.atlassian.net/browse/PHEE-374?atlOrigin=eyJpIjoiZGRlOTM3NDM0ZjgwNDIwMTk0Y2JiZjM3OTIwODFkNDQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-374 Update readme for checkstyle and spotless

src/main/java/org/mifos/connector/channel/api/definition/CollectionApi.java, src/main/java/org/mifos/connector/channel/api/implementation/CollectionApiController.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeVariables.java, src/main/resources/application.yml
In addition to Mpesa, other similar flows (ex. Airtel Money, MTN MoMo, etc) can be supported by parameterizing the payment scheme.
This PR adds support for an optional `X-Payment-Scheme` header whose value will determine which bpmn flow will be started when a collection request is received.
Jira ticket: https://mifosforge.jira.com/browse/PHEE-249
@avikganguly01 @fynmanoj @ankita10r please review
=> PHEE-249 Parameterize collection payment scheme

src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/resources/application-tenants.yml
[PHEE-404 Use tenant & useCase config to get flow for channel collection api](https://fynarfin.atlassian.net/browse/PHEE-404?atlOrigin=eyJpIjoiYWJjN2RmMzBmYmJmNDAzZjkwMzExOTc3OWI1YTA5MjMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-404 Use tenant & useCase config to get flow for channel collection api

build.gradle
(https://mifosforge.jira.com/browse/GOV-134)
* Added Liveness and readiness probes to Application yaml
* Added actuators dependency in gradle file
=> #GOV-134 Enable liveness and readiness

.circleci/config.yml
[PHEE-386 Update circle CI config of micro services with integration test](https://fynarfin.atlassian.net/browse/PHEE-386?atlOrigin=eyJpIjoiZjczZjdlOWI5MTA1NDgyN2I3OTQ4M2NiMzk5ZTVkMGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PHEE-373 build & host ph-ee-engine chart, g2p-sandbox chart and G2P sand…](https://fynarfin.atlassian.net/browse/PHEE-373?atlOrigin=eyJpIjoiYmVjYTRkYWEyNmMxNGIyNWI2ODk5OTI3OGMxMTdjODYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-386,373 Update circle CI config of with integration test and host charts

.circleci/config.yml
[PHEE-386 Update circle CI config of micro services with integration test](https://fynarfin.atlassian.net/browse/PHEE-386?atlOrigin=eyJpIjoiZjczZjdlOWI5MTA1NDgyN2I3OTQ4M2NiMzk5ZTVkMGYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-386 Upgrading the gradle command in CI config

src/main/resources/application-tenants.yml
[PHEE-422 Create minimalMockTransferRequest BPMN, its workers, required confi…](https://fynarfin.atlassian.net/browse/PHEE-422?atlOrigin=eyJpIjoiMzE5OWM2YWY3MGMyNGIwMDgxZDk2YmRjYWI3ZWI4ZjIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-422 added minimalMockTransferRequest configuration

src/main/java/org/mifos/connector/ChannelConnectorApplication.java, src/main/java/org/mifos/connector/channel/api/implementation/TransferApiController.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java, src/main/java/org/mifos/connector/gsmastub/api/ApiOriginFilter.java
Fixing broken api origin filter added under [GOV-265](https://mifosforge.jira.com/browse/GOV-265)
[GOV-265]: https://mifosforge.jira.com/browse/GOV-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GOV-265: Fixed broken api origin filter

.circleci/config.yml
=> V1.7.1 release

src/main/java/org/mifos/connector/channel/api/definition/GSMATransactionApi.java, src/main/java/org/mifos/connector/channel/api/implementation/GSMATransactionApiController.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
[PHEE-440 Create a worker to send the callback in ams_mifos](https://fynarfin.atlassian.net/browse/PHEE-440?atlOrigin=eyJpIjoiZDljNTEwYWM1Mjg2NDI4MmFlYjZkOGE4YmUyYWU1YzIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> PHEE-440 Create a worker to send the callback in ams_mifos

src/main/java/org/mifos/connector/channel/api/definition/TransferApi.java, src/main/java/org/mifos/connector/channel/api/implementation/TransferApiController.java, src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/camel/routes/ChannelRouteBuilder.java
=> GOV-517 Adding Header in Transfer API

.circleci/config.yml
[PHEE-490 Publish helm chart with jira ticket from circleci](https://fynarfin.atlassian.net/browse/PHEE-490?atlOrigin=eyJpIjoiMDAwNWMwNjNmN2NhNGUyZWExZDU4NWIwNGU3MmU5ZjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-490] Publish helm chart with jira ticket from circleci

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
=> [GOV-78] Fix for P2P

.circleci/config.yml, src/main/java/org/mifos/connector/channel/api/implementation/CollectionApiController.java, src/main/java/org/mifos/connector/channel/api/implementation/GSMATransactionApiController.java, src/main/java/org/mifos/connector/channel/api/implementation/PartyRegistrationApiController.java, src/main/java/org/mifos/connector/channel/api/implementation/TransactionApiController.java, src/main/java/org/mifos/connector/channel/api/implementation/TransferApiController.java, src/main/java/org/mifos/connector/channel/gsma_api/GSMADepositAPIController.java, src/main/java/org/mifos/connector/channel/gsma_api/GSMATransferAPIController.java, src/main/java/org/mifos/connector/channel/model/GlobalExceptionMapperDTO.java, src/main/java/org/mifos/connector/channel/utils/ConnectorChannelEnum.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeProcessStarter.java, src/main/java/org/mifos/connector/exceptionmapper/GlobalExceptionMapper.java
[PHEE-526 BPMN 500 issue fix in Connector-Channel](https://fynarfin.atlassian.net/browse/PHEE-526?atlOrigin=eyJpIjoiOWE0ODM1YzRjY2YzNDY1N2I0ZjRhNzBmOTk3Y2E3YjMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-526] Fix for BPMN 500 issue

src/main/resources/application.yml
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
=> [PHEE-556] Fix bpmn name in channel configuration

src/main/java/org/mifos/connector/channel/camel/routes/GSMAChannelRouteBuilder.java, src/main/java/org/mifos/connector/channel/gsma_api/GSMATransferAPI.java, src/main/java/org/mifos/connector/channel/gsma_api/GSMATransferAPIController.java
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
=> [GOV-78] Fix for batch id header

src/main/java/org/mifos/connector/channel/camel/config/CamelProperties.java, src/main/java/org/mifos/connector/channel/zeebe/ZeebeWorkers.java
[PHEE-583 Voucher paymentMobality not found.](https://fynarfin.atlassian.net/browse/PHEE-583?atlOrigin=eyJpIjoiNDhmNTRiNWI2OTVlNDkwNTk1ZWM2ZmQ1ZGZiY2RiYjUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
=> [PHEE-583] Voucher paymentMobality not found

src/main/resources/application.yml
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
=> [PHEE-568] Updated destination to include new tenant for payee FSP for MM
